import project.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import java.sql.ResultSet;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmadullah taheri
 */
public class team_leader_registration extends javax.swing.JFrame {
public void Referesh() {  
    jTextField1.setText("");  
  //  jTextField2.setText("");  
   // jTextField3.setText("");  
}
    /**
     * Creates new form manageRoom
     */
    
    
    
    public team_leader_registration() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        jTextField05.setEditable(false);
        SimpleDateFormat myFormat= new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal=Calendar.getInstance();
        jTextField05.setText(myFormat.format(cal.getTime()));
    
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField05 = new javax.swing.JTextField();
        jComboBox01 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox02 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField01 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField02 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField03 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField04 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 30, 40, -1));

        jTable1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "نام سرتیم", "تعداد مامورین", "روز اداری", "تایم اداری", "بدیل سرتیم", "مسوولیت سرتیم", "تاریخ راجستر سرتیم جدید"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(1);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1370, 320));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel2.setText("تاریخ ثبت سرتیم جدید ");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 160, 30));

        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/راجستر.jpg"))); // NOI18N
        jButton2.setText("ذخیره");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 110, 40));

        jTextField05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField05ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField05, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 230, 30));

        jComboBox01.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jComboBox01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "یک نفر", "دو نفر", "سه نفر", "چهار نفر", "پنج نفر", "شش نفر", "هفت نفر", "هشت نفر" }));
        getContentPane().add(jComboBox01, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 80, 30));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel7.setText("تایم اداری تعیین شده ");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 300, 150, 30));

        jComboBox02.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jComboBox02.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "شنبه", "یکشنبه", "دوشنبه", "سه شنبه", "چهارشنبه", "پنج شنبه", "جمعه" }));
        getContentPane().add(jComboBox02, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 80, 30));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel8.setText("  تعداد مأمورین ");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 110, 30));

        jTextField01.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        getContentPane().add(jTextField01, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 170, 30));

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel9.setText("بدیل - سرتیم ");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 110, 30));

        jTextField02.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        getContentPane().add(jTextField02, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 170, 30));

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel10.setText("روز اداری تعیین شده ");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 150, 30));

        jTextField03.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        getContentPane().add(jTextField03, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, 30));

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel11.setText("مسوولیت - سرتیم ");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 140, 30));

        jTextField04.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jTextField04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField04ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField04, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 230, 30));

        jLabel3.setFont(new java.awt.Font("MRT_Classic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/سرتیم.jpg"))); // NOI18N
        jLabel3.setText("بخش راجستر سرتیم جدید ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 420, 70));

        jButton7.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.jpg"))); // NOI18N
        jButton7.setText("ایجاد تغییر");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 120, 40));

        jButton6.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton6.setText("حذف");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 390, 100, 40));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel1.setText("ID ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, 40));

        jTextField1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(78, 152, 103)));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 94, 40));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel5.setText("نام و تخلص سرتیم جدید ");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 180, 30));

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int id=0;
        String team_leader_name=jTextField01.getText();
        String team_leader_agents=(String)jComboBox01.getSelectedItem();
        String team_leader_managements_day=(String)jComboBox02.getSelectedItem();
        String team_leader_managements_time=jTextField02.getText();
        String team_leader_manager_name=jTextField03.getText();
        String team_leader_responsibility=jTextField04.getText();
        String team_leader_registration_day=jTextField05.getText();
        String Query="select id from team_leader_registration ";
        try
        {
            ResultSet rs=Select.getData(Query);
            
            while(rs.next())
                id=rs.getInt(1);
                id=id+1;
        
                  if(team_leader_name.equals("") || team_leader_managements_time.equals("") || team_leader_manager_name.equals("") || team_leader_responsibility.equals(""))
            JOptionPane.showMessageDialog(null,"Every field is Required");
      
        else
        {
            
            
         Query="insert into team_leader_registration values('"+id+"','"+team_leader_name+"','"+team_leader_agents+"','"+team_leader_managements_day+"','"+team_leader_managements_time+"','"+team_leader_manager_name+"','"+team_leader_responsibility+"','"+team_leader_registration_day+"','Not Booked')";
            
            InsertUpdateDelete.setData(Query,"Registered Successfully");
            setVisible(false);
            new team_leader_registration().setVisible(true);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }    

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=Select.getData("select *from team_leader_registration");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                
            model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
            
            }
            rs.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }    
    }//GEN-LAST:event_formComponentShown

    private void jTextField05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField05ActionPerformed

    private void jTextField04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField04ActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            // establish connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/dawat", "root", "123456");
            Statement stmt = con.createStatement();
            stmt.execute("UPDATE team_leader_registration SET team_leader_name='" +jTextField01.getText()+ "',team_leader_agents='" +jComboBox01.getSelectedItem()+ "' ,team_leader_managements_day='" +jComboBox02.getSelectedItem()+ "' ,team_leader_managements_time='" +jTextField03.getText()+ "' ,team_leader_manager_name='" +jTextField04.getText()+ "' ,team_leader_responsibility='" +jTextField05.getText()+ "' ,team_leader_registration_day='" +jTextField1.getText()+ "' WHERE id='" + jTextField1.getText() + "'");
            JOptionPane.showMessageDialog(null, "Record is updated...");
            stmt.close();
            con.close();
            Referesh(); //Calling Referesh() method
            setVisible(false);
            new team_leader_registration().setVisible(true);
        } catch (SQLException | ClassNotFoundException se) {
            JOptionPane.showMessageDialog(null, se);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            // establish connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/dawat", "root", "123456");
            Statement statement = con.createStatement();
            statement.executeUpdate("DELETE FROM team_leader_registration WHERE id=" + jTextField1.getText() + "");
            JOptionPane.showMessageDialog(null, "Record deleted...");
            statement.close();
            con.close();
            Referesh(); //Calling Referesh() method
            setVisible(false);
            new team_leader_registration().setVisible(true);
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(team_leader_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(team_leader_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(team_leader_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(team_leader_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new team_leader_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox01;
    private javax.swing.JComboBox<String> jComboBox02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField01;
    private javax.swing.JTextField jTextField02;
    private javax.swing.JTextField jTextField03;
    private javax.swing.JTextField jTextField04;
    private javax.swing.JTextField jTextField05;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
